### PR TITLE
Setup, convert and validate batches of XML files

### PR DESCRIPTION
**Pull request by gnott**
Early working drafts of a method to convert and test batches of XML files ability to open the files in Texture. There are some changes to `xquery/elife2dar.xq` for input file and zorba configuration. I think it is automatically merging the changes to the latest Xquery file. 

@FAtherden-eLife if you would like to please confirm it is ok to merge?

### CODE REVIEW

**Review by fred-atherden — COMMENTED** [review]
@gnott can the two changes added [in this commit](https://github.com/elifesciences/elife-jats-2-dar-jats/commit/cc0ad047e32e89c03e5b565241dc904bb07e62a1) be included in the XQuery? No worries if not, I can always change this later.

**Comment by gnott** [comment]
Those lines should be merged automatically since they do not conflict with the ones I edited in the top and bottom fo the Xquery file.

**Comment by fred-atherden** [comment]
Oh I see, sorry for the misunderstanding. Then please go ahead!

**Comment by gnott** [comment]
Here goes!

**Pull request merged**
